apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/k8s-device-plugin
    chart: nvidia-device-plugin
    targetRevision: 0.20.1
    helm:
      values: |
        runtimeClassName: nvidia
        nodeSelector:
          gpu-worker: "true"
        affinity: null
        tolerations:
          - key: gpu-worker
            operator: Equal
            value: "true"
            effect: NoSchedule
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
          - key: CriticalAddonsOnly
            operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-device-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
