apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-ingress
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://bedag.github.io/helm-charts/
      chart: raw
      targetRevision: 2.0.2
      helm:
        values: |
          resources:
            - apiVersion: v1
              kind: Service
              metadata:
                name: alertmanager-mini-external
                namespace: default
              spec:
                ports:
                  - port: 9093
                    targetPort: 9093
                    protocol: TCP
            - apiVersion: discovery.k8s.io/v1
              kind: EndpointSlice
              metadata:
                name: alertmanager-mini-external-1
                namespace: default
                labels:
                  kubernetes.io/service-name: alertmanager-mini-external
              addressType: IPv4
              endpoints:
                - addresses:
                    - 10.100.20.18
                  conditions:
                    ready: true
              ports:
                - name: ""
                  port: 9093
                  protocol: TCP
            - apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: alertmanager-mini-ingress-amer-dev
                namespace: default
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                  external-dns.alpha.kubernetes.io/hostname: alertmanager.amer.dev,alerts.amer.dev
                  external-dns.kubernetes.io/target: 10.100.20.171
                  external-dns.alpha.kubernetes.io/ttl: "300"
              spec:
                tls:
                  - hosts:
                      - alertmanager.amer.dev
                      - alerts.amer.dev
                    secretName: alertmanager-amer-dev-tls
                rules:
                  - host: alertmanager.amer.dev
                    http:
                      paths:
                        - path: /
                          pathType: Prefix
                          backend:
                            service:
                              name: alertmanager-mini-external
                              port:
                                number: 9093
                  - host: alerts.amer.dev
                    http:
                      paths:
                        - path: /
                          pathType: Prefix
                          backend:
                            service:
                              name: alertmanager-mini-external
                              port:
                                number: 9093

            - apiVersion: v1
              kind: Service
              metadata:
                name: comfyui-external
                namespace: default
              spec:
                ports:
                  - port: 8188
                    targetPort: 8188
                    protocol: TCP
            - apiVersion: discovery.k8s.io/v1
              kind: EndpointSlice
              metadata:
                name: comfyui-external-1
                namespace: default
                labels:
                  kubernetes.io/service-name: comfyui-external
              addressType: IPv4
              endpoints:
                - addresses:
                    - 10.100.20.19
                  conditions:
                    ready: true
              ports:
                - name: ""
                  port: 8188
                  protocol: TCP
            - apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: comfyui-ingress-amer-dev
                namespace: default
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                  external-dns.alpha.kubernetes.io/hostname: comfy.amer.dev
                  external-dns.kubernetes.io/target: 10.100.20.171
                  external-dns.alpha.kubernetes.io/ttl: "300"
              spec:
                tls:
                  - hosts:
                      - comfy.amer.dev
                    secretName: comfy-amer-dev-tls
                rules:
                  - host: comfy.amer.dev
                    http:
                      paths:
                        - path: /
                          pathType: Prefix
                          backend:
                            service:
                              name: comfyui-external
                              port:
                                number: 8188

            - apiVersion: v1
              kind: Service
              metadata:
                name: couchdb-mini-external
                namespace: default
              spec:
                ports:
                  - port: 5984
                    targetPort: 5984
                    protocol: TCP
            - apiVersion: discovery.k8s.io/v1
              kind: EndpointSlice
              metadata:
                name: couchdb-mini-external-1
                namespace: default
                labels:
                  kubernetes.io/service-name: couchdb-mini-external
              addressType: IPv4
              endpoints:
                - addresses:
                    - 10.100.20.18
                  conditions:
                    ready: true
              ports:
                - name: ""
                  port: 5984
                  protocol: TCP
            - apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: couchdb-mini-ingress-amer-dev
                namespace: default
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                  external-dns.alpha.kubernetes.io/hostname: couchdb.amer.dev
                  external-dns.kubernetes.io/target: 10.100.20.171
                  external-dns.alpha.kubernetes.io/ttl: "300"
              spec:
                tls:
                  - hosts:
                      - couchdb.amer.dev
                    secretName: couchdb-amer-dev-tls
                rules:
                  - host: couchdb.amer.dev
                    http:
                      paths:
                        - path: /
                          pathType: Prefix
                          backend:
                            service:
                              name: couchdb-mini-external
                              port:
                                number: 5984

            - apiVersion: v1
              kind: Service
              metadata:
                name: grafana-mini-external
                namespace: default
              spec:
                ports:
                  - port: 3000
                    targetPort: 3000
                    protocol: TCP
            - apiVersion: discovery.k8s.io/v1
              kind: EndpointSlice
              metadata:
                name: grafana-mini-external-1
                namespace: default
                labels:
                  kubernetes.io/service-name: grafana-mini-external
              addressType: IPv4
              endpoints:
                - addresses:
                    - 10.100.20.18
                  conditions:
                    ready: true
              ports:
                - name: ""
                  port: 3000
                  protocol: TCP
            - apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: grafana-mini-ingress-amer-dev
                namespace: default
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                  external-dns.alpha.kubernetes.io/hostname: grafana.amer.dev
                  external-dns.kubernetes.io/target: 10.100.20.171
                  external-dns.alpha.kubernetes.io/ttl: "300"
              spec:
                tls:
                  - hosts:
                      - grafana.amer.dev
                    secretName: grafana-amer-dev-tls
                rules:
                  - host: grafana.amer.dev
                    http:
                      paths:
                        - path: /
                          pathType: Prefix
                          backend:
                            service:
                              name: grafana-mini-external
                              port:
                                number: 3000

            - apiVersion: v1
              kind: Service
              metadata:
                name: ha-mini-external
                namespace: default
              spec:
                ports:
                  - port: 8123
                    targetPort: 8123
                    protocol: TCP
            - apiVersion: discovery.k8s.io/v1
              kind: EndpointSlice
              metadata:
                name: ha-mini-external-1
                namespace: default
                labels:
                  kubernetes.io/service-name: ha-mini-external
              addressType: IPv4
              endpoints:
                - addresses:
                    - 10.100.20.18
                  conditions:
                    ready: true
              ports:
                - name: ""
                  port: 8123
                  protocol: TCP
            - apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: ha-mini-ingress-amer-dev
                namespace: default
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                  external-dns.alpha.kubernetes.io/hostname: ha.amer.dev
                  external-dns.kubernetes.io/target: 10.100.20.171
                  external-dns.alpha.kubernetes.io/ttl: "300"
              spec:
                tls:
                  - hosts:
                      - ha.amer.dev
                    secretName: ha-amer-dev-tls
                rules:
                  - host: ha.amer.dev
                    http:
                      paths:
                        - path: /
                          pathType: Prefix
                          backend:
                            service:
                              name: ha-mini-external
                              port:
                                number: 8123

            - apiVersion: v1
              kind: Service
              metadata:
                name: z2m-external
                namespace: default
              spec:
                ports:
                  - port: 8099
                    targetPort: 8099
                    protocol: TCP
            - apiVersion: discovery.k8s.io/v1
              kind: EndpointSlice
              metadata:
                name: z2m-external-1
                namespace: default
                labels:
                  kubernetes.io/service-name: z2m-external
              addressType: IPv4
              endpoints:
                - addresses:
                    - 10.100.20.18
                  conditions:
                    ready: true
              ports:
                - name: ""
                  port: 8099
                  protocol: TCP
            - apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: z2m-ingress-amer-dev
                namespace: default
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                  external-dns.alpha.kubernetes.io/hostname: z2m-dean-1.amer.dev
                  external-dns.kubernetes.io/target: 10.100.20.171
                  external-dns.alpha.kubernetes.io/ttl: "300"
              spec:
                tls:
                  - hosts:
                      - z2m-dean-1.amer.dev
                    secretName: z2m-dean-1-amer-dev-tls
                rules:
                  - host: z2m-dean-1.amer.dev
                    http:
                      paths:
                        - path: /
                          pathType: Prefix
                          backend:
                            service:
                              name: z2m-external
                              port:
                                number: 8099
            - apiVersion: v1
              kind: Service
              metadata:
                name: komodo-external
                namespace: default
              spec:
                ports:
                  - port: 9120
                    targetPort: 9120
                    protocol: TCP
            - apiVersion: discovery.k8s.io/v1
              kind: EndpointSlice
              metadata:
                name: komodo-external-1
                namespace: default
                labels:
                  kubernetes.io/service-name: komodo-external
              addressType: IPv4
              endpoints:
                - addresses:
                    - 10.100.20.18
                  conditions:
                    ready: true
              ports:
                - name: ""
                  port: 9120
                  protocol: TCP
            - apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: komodo-ingress-amer-dev
                namespace: default
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                  external-dns.alpha.kubernetes.io/hostname: komodo.amer.dev
                  external-dns.kubernetes.io/target: 10.100.20.171
                  external-dns.alpha.kubernetes.io/ttl: "300"
              spec:
                tls:
                  - hosts:
                      - komodo.amer.dev
                    secretName: komodo-amer-dev-tls
                rules:
                  - host: komodo.amer.dev
                    http:
                      paths:
                        - path: /
                          pathType: Prefix
                          backend:
                            service:
                              name: komodo-external
                              port:
                                number: 9120
            - apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: ha-pub-ingress-amer-dev
                namespace: default
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
              spec:
                tls:
                  - hosts:
                      - ha.pub.amer.dev
                    secretName: ha-pub-amer-dev-tls
                rules:
                  - host: ha.pub.amer.dev
                    http:
                      paths:
                        - path: /auth/
                          pathType: Prefix
                          backend:
                            service:
                              name: ha-mini-external
                              port:
                                number: 8123
                        - path: /api/google_assistant
                          pathType: Prefix
                          backend:
                            service:
                              name: ha-mini-external
                              port:
                                number: 8123
            - apiVersion: externaldns.k8s.io/v1alpha1
              kind: DNSEndpoint
              metadata:
                name: ha-pub-amer-dev
                namespace: default
              spec:
                endpoints:
                  - dnsName: ha.pub.amer.dev
                    recordTTL: 300
                    recordType: A
                    targets:
                      - 67.250.70.153

            - apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: pubhooks-github-ingress-amer-dev
                namespace: default
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
              spec:
                tls:
                  - hosts:
                      - pubhooks.amer.dev
                    secretName: pubhooks-amer-dev-tls
                rules:
                  - host: pubhooks.amer.dev
                    http:
                      paths:
                        - path: /listener/github/
                          pathType: Prefix
                          backend:
                            service:
                              name: komodo-external
                              port:
                                number: 9120
            - apiVersion: externaldns.k8s.io/v1alpha1
              kind: DNSEndpoint
              metadata:
                name: pubhooks-amer-dev
                namespace: default
              spec:
                endpoints:
                  - dnsName: pubhooks.amer.dev
                    recordTTL: 300
                    recordType: A
                    targets:
                      - 67.250.70.153
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
